// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/fulfil.js', ['ng.tryton.fulfil', 'ng.tryton.fulfil.datatype'], ['goog.date.Date', 'goog.date.DateTime', 'goog.date.Interval', 'goog.date.UtcDateTime'], false);
goog.addDependency('../../../../src/pyson.js', ['ng.tryton.PYSON'], [], false);
goog.addDependency('../../../../src/tryton.js', ['ng.tryton'], ['ng.tryton.PYSON', 'ng.tryton.fulfil'], false);
