// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/fulfil.js', ['angular.tryton.fulfil', 'angular.tryton.fulfil.datatype'], ['goog.date.Date', 'goog.date.DateTime', 'goog.date.Interval', 'goog.date.UtcDateTime'], false);
goog.addDependency('../../../../src/tryton.js', ['angular.tryton'], ['angular.tryton.fulfil'], false);
